name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: ruwanvm/notify-action@master
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "default message Hello default webhook"