name: Integration Test
on: [push, pull_request]
jobs:
  integration_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Self test
        id: selftest
        uses: ruwanvm/notify-action@master
        with:
          webhook: ${{ secrets.CI_WEBHOOK_URL }}
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.results }}" == "default message is send with status 200"