on: [workflow_dispatch]

jobs:
  teams_message_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Teams bessage Validation
        id: teams_message
        uses: ruwanvm/notify-action@teams
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
      - name: Check teams message send results
        run: echo "${{ steps.teams_message.outputs.results }}"